export const PRODUCT_MESSAGES = {
  success_image_save: 'Image saved successfully',
  success_image_delete: 'Image deleted successfully',
  success_image_update: 'Image updated successfully',
  success_update: 'Product updated successfully',
  success_delete: 'Product deleted successfully',
  success_create: 'Product created successfully',
  success_category_delete: 'Category deleted successfully',
  success_category_add: 'Category added to product successfully',

  error_not_found: 'Product not found',
  error_image_not_found: 'Image not found',
  error_create: 'Error while creating product',
  error_filter: 'Error while filtering products',
  error_update: 'Error while updating product',
  error_delete: 'Error while deleting product',
  error_image_save: 'Error while saving images',
  error_image_update: 'Error while updating image',
  error_image_delete: 'Error while deleting image',
  error_category_find: 'Error while finding product',
  error_name_find: 'Error while finding product by name',
  error_name_exists: 'Product with this name already exists',
  error_category_not_found: 'Category that product belongs to not found',
  error_category_adding_to_product: 'Error while adding category to product',
  error_category_deleting_from_product: 'Error while deleting category from product',
};
